function Desc()
{
    return(
        <div style={{textAlign:"center"}}>
          <img src="https://res.klook.com/images/fl_lossy.progressive,q_65/c_fill,w_1200,h_630/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/tsah7c9evnal289z5fig/IMG%20Worlds%20of%20Adventure%20Admission%20Ticket%20in%20Dubai%20-%20Klook.jpg" width="100%" height="300px"></img>
            <h2 style={{color:'red'}}>Home Page</h2>
      <p style={{width:'90%', margin:'auto', textAlign:'justify'}}>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus sint est laboriosam voluptatibus tempora molestiae architecto, eveniet dignissimos temporibus! Voluptatum commodi nulla excepturi tempore explicabo, unde odio autem? Neque, quia.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac justo sit amet magna sollicitudin pellentesque at ut libero. Quisque luctus felis at justo fermentum imperdiet. Proin elementum et nisl at pulvinar. Proin a tempus nisi, a lacinia nibh. Duis vulputate consequat fringilla. Nunc ultrices scelerisque faucibus. Donec scelerisque sapien sapien, non ultricies urna pulvinar vel. Duis venenatis posuere enim in condimentum. Suspendisse vestibulum elementum magna, quis ullamcorper nisi facilisis quis. Nam hendrerit, libero sed porttitor feugiat, quam metus viverra lorem, ut laoreet ante lectus nec mauris. Etiam euismod cursus ex condimentum pretium.

Ut sit amet odio fermentum, ultrices magna a, mattis ante. Proin ultricies volutpat elementum. Vestibulum maximus ex in finibus fermentum. Suspendisse pulvinar vulputate ipsum vitae posuere. Nunc ut nunc lorem. Donec aliquet augue risus, id ornare ipsum condimentum eu. In aliquam congue lacus a facilisis. Aliquam sed malesuada nisi.

Vivamus blandit pulvinar mollis. Pellentesque rutrum justo ut est eleifend eleifend eu condimentum libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras dictum velit arcu, nec tempus sapien ornare eu. Pellentesque accumsan vehicula nisl sit amet iaculis. Proin dignissim, lacus ullamcorper dictum vestibulum, felis purus pulvinar diam, ut pretium arcu leo commodo ipsum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus luctus nisi tincidunt augue facilisis dapibus. Suspendisse vitae arcu tempor leo eleifend posuere at ut ante. Nunc laoreet aliquam nisi, commodo consectetur justo fringilla id. Mauris porttitor, mi et fermentum condimentum, leo diam mollis nunc, condimentum pellentesque orci magna sed ex. Morbi pulvinar libero nec eleifend ullamcorper.

Praesent sapien elit, mollis a dui et, elementum mollis risus. Vivamus vulputate ipsum velit, vitae consequat est luctus quis. Vivamus consectetur mauris vitae sapien ultrices, nec porta ex tempor. Aliquam facilisis feugiat libero, ut dictum leo laoreet ut. Morbi nec orci mollis, interdum velit ut, congue magna. Aenean commodo diam eu orci suscipit accumsan. Quisque fringilla nibh a erat auctor, id imperdiet turpis suscipit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas interdum odio vulputate, tristique ipsum sit amet, efficitur magna. Vestibulum eget metus id turpis tincidunt mattis. In aliquam ante quis nibh maximus, sit amet malesuada libero feugiat. Integer sed metus nec eros pretium sagittis ut at tortor. Fusce eu mauris eu massa posuere interdum.</p>
            <p style={{width:'90%', margin:'auto', textAlign:'justify'}}>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus sint est laboriosam voluptatibus tempora molestiae architecto, eveniet dignissimos temporibus! Voluptatum commodi nulla excepturi tempore explicabo, unde odio autem? Neque, quia.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac justo sit amet magna sollicitudin pellentesque at ut libero. Quisque luctus felis at justo fermentum imperdiet. Proin elementum et nisl at pulvinar. Proin a tempus nisi, a lacinia nibh. Duis vulputate consequat fringilla. Nunc ultrices scelerisque faucibus. Donec scelerisque sapien sapien, non ultricies urna pulvinar vel. Duis venenatis posuere enim in condimentum. Suspendisse vestibulum elementum magna, quis ullamcorper nisi facilisis quis. Nam hendrerit, libero sed porttitor feugiat, quam metus viverra lorem, ut laoreet ante lectus nec mauris. Etiam euismod cursus ex condimentum pretium. Ut sit amet odio fermentum, ultrices magna a, mattis ante. Proin ultricies volutpat elementum. Vestibulum maximus ex in finibus fermentum. Suspendisse pulvinar vulputate ipsum vitae posuere. Nunc ut nunc lorem. Donec aliquet augue risus, id ornare ipsum condimentum eu. In aliquam congue lacus a facilisis. Aliquam sed malesuada nisi. Vivamus blandit pulvinar mollis. Pellentesque rutrum justo ut est eleifend eleifend eu condimentum libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras dictum velit arcu, nec tempus sapien ornare eu. Pellentesque accumsan vehicula nisl sit amet iaculis.</p>
        </div>
    )
}
export default Desc